language: cpp
notifications:
  slack: gamepros:8J6TWKw3BdVJkXqRQ8hPNa7r
matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['george-edison55-precise-backports', 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages:
            - xorg-dev
            - libgl1-mesa-dev
            - pkg-config
            - clang-3.6
      env: PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/glfw3/lib/pkgconfig" COMPILER=clang-3.6
    - os: osx
      compiler: clang
      env: COMPILER=clang

cache:
  directories:
  - $HOME/glfw3
before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew install glfw3; brew install llvm37; brew link --force llvm37; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then bash travis_get_glfw3.sh; fi

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then export CXX=$COMPILER; fi
  - ${CXX} --version
  - sh ./build.sh
