language: cpp
compiler: clang
notifications:
  slack: gamepros:8J6TWKw3BdVJkXqRQ8hPNa7r

os: 
  - osx
  - linux
addons:
  apt:
    packages:
      - cmake
      - libglfw3
      - llvm-3.4
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 glfw3 && brew link --force llvm35; fi

script: ./build.sh