language: cpp
compiler: clang
notifications:
  slack: gamepros:8J6TWKw3BdVJkXqRQ8hPNa7r
env:
  - PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/glfw3/lib/pkgconfig"
os:
  - linux
  - osx
addons:
  sources:
    - george-edison55-precise-backports
  apt:
    packages:
      - cmake
      - xorg-dev
      - libgl1-mesa-dev
      - pkg-config
cache:
  directories:
  - $HOME/glfw3
before_install:
  - echo $LANG
  - echo $LC_ALL
  - ls -R $HOME
  - echo $PKG_CONFIG_PATH
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install  glfw3 ; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then bash travis_get_glfw3.sh; fi

before_script:
  - ls -R $HOME/glfw3

script: ./build.sh
